# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "tag-orders-on-a-daily"
client_id = "fd8bf57c7ceb4ba2d5d0f506ceddb27d"
application_url = "https://9f1e-79-174-251-211.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_orders, read_orders, read_customers, write_customers, read_all_orders"

[auth]
redirect_urls = [
  "https://9f1e-79-174-251-211.ngrok-free.app/auth/callback",
  "https://9f1e-79-174-251-211.ngrok-free.app/auth/shopify/callback",
  "https://9f1e-79-174-251-211.ngrok-free.app/api/auth/callback",
  "https://9f1e-79-174-251-211.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "benitos-santos.myshopify.com"
